import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const CreateGame = () => {
  const [email, setEmail] = useState("");
  const createGameMutation = trpc.useMutation(["game.create"]);

  return (
    <div>
      <input
        type="email"
        name="invite"
        id="invite"
        value={email}
        onChange={(e) => {
          setEmail(e.target.value);
          console.log(email);
        }}
      />
      <button
        onClick={() => {
          createGameMutation.mutate({ email });
          console.log(email);
        }}
      >
        Create Game
      </button>
    </div>
  );
};

const PlayerInfo: React.FC<{ userId: string }> = ({ userId }) => {
  const user = trpc.useQuery(["user.get", { id: userId }]);
  return (
    <div>
      <p>{user.data?.name}</p>
      <p>{user.data?.email}</p>
    </div>
  );
};

const GameList = () => {
  const games = trpc.useQuery(["game.getMine"]);
  if (games.isLoading) {
    return <div>loading...</div>;
  }

  return (
    <div>
      {games.data?.map((game) => (
        <div key={game.id} className="border">
          <div>{game.id}</div>
          <div>
            <p>Players:</p>
            {game.players.map((p) => {
              if (!p.userId) {
                return null;
              }

              return (
                <div key={p.id}>
                  <PlayerInfo userId={p.userId} />
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
};

const HomeContents = () => {
  const { data } = useSession();

  if (!data) {
    return <button onClick={() => signIn()}>Logga in</button>;
  }

  return (
    <>
      <div>Hej {data.user?.name}!</div>
      <button onClick={() => signOut()}>Logga ut</button>
      <CreateGame />

      <GameList />
    </>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gul Bil</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents />
    </>
  );
};

export default Home;
